sonar.projectKey=ApexForge-CloudOps-Portal
sonar.projectName=ApexForge CloudOps Portal
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.xunit.reportPath=reports/pytest.xml
sonar.exclusions=**/__pycache__/**,**/*.pyc,app/static/**,app/templates/**,.trivy-cache/**,.scannerwork/**,.pip-cache/**,.ci-venv/**,reports/**,.deploy-work/**,deploy/environment*.json
