#!/usr/bin/env python3
"""Refresh the complete wheel lock inside the reviewed Python base (linux/amd64)."""
import email
import hashlib
from pathlib import Path
import subprocess
import sys
import tempfile
import zipfile


def main() -> None:
    with tempfile.TemporaryDirectory() as directory:
        subprocess.run([sys.executable, "-m", "pip", "download", "--only-binary=:all:",
                        "--dest", directory, "-r", "requirements.in"], check=True)
        rows = []
        for wheel in sorted(Path(directory).glob("*.whl")):
            with zipfile.ZipFile(wheel) as archive:
                metadata_path = next(name for name in archive.namelist() if name.endswith(".dist-info/METADATA"))
                metadata = email.message_from_bytes(archive.read(metadata_path))
            digest = hashlib.sha256(wheel.read_bytes()).hexdigest()
            rows.append(f"{metadata['Name']}=={metadata['Version']} --hash=sha256:{digest}")
        Path("requirements.txt").write_text(
            "# Generated by deploy/lock-dependencies.py; CPython 3.12, linux/amd64 wheels only.\n"
            + "\n".join(sorted(rows, key=str.lower)) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
